version: '3.9'

services:
 microservice:
    build:
      context: ./
    image: async-few-threads-microservice
    container_name: async-recommendation
    networks:
      - my_network
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


networks:
  my_network: